### ISSUE TITLE
Ошибка в routes_api при создании модуля

### ISSUE THREAD

**Issue by KingLefff** [Yurich84/laravel-vue-spa-skeleton#13]
### Описание ошибки
После создания модуля, при запросе данных с frontend на backend, происходит ошибка. Точнее сам запрос возвращает код 200, но в ответ приходит html страница и при разборе ответа, для вывода данных в таблицу вылетала ошибка, ругается что нет total.

### Пример
Название модуля - _ListPharm_
При создании в 
**routes_api.php**: `Route::apiResource('list-pharms', 'ListPharmController');`
**api.index.js**: `const API_ENDPOINT = 'listPharms'`

Соответственно запрос уходит на **api/v1/listPharms**, но такого пути нет, из-за этого ошибка.

### Варианты решения
1. Изменить в файле **routes.api.stub** `Route::apiResource('dummy-plural', 'DummySingularController');` на `Route::apiResource('dummyVariablePlural', 'DummySingularController');`
2. Изменить в файле **MakeModuleCommand** (_195 строка_)
`lcfirst($this->module->plural()->snake('-'))` на `lcfirst($this->module->pluralStudly())`
3. Каждый раз не забывать отредактировать **routes_api.php** созданного модуля

**Comment by Yurich84** [comment]
Первый вариант выглядит отлично, не хотите создать пулреквест?

**Comment by KingLefff** [comment]
@Yurich84 Да, хорошо
