### ISSUE TITLE
Wrong middleware name in BroadcastServiceProvider. 

### ISSUE THREAD

**Issue by BotStop** [Yurich84/laravel-vue-spa-skeleton#37]
Is it correct middleware? I didn't find any with that name.
https://github.com/Yurich84/laravel-vue-spa-skeleton/blob/29d7f80bb58097230e83593881d9dc7666610085/app/Providers/BroadcastServiceProvider.php#L17

I think u missed 'auth:'
https://laravel.com/docs/9.x/sanctum#authorizing-private-broadcast-channels

**Comment by Yurich84** [comment]
You are right.
